// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	CHESS_GAME: DurableObjectNamespace /* ChessGame from chess-worker */;
	RPC_SERVICE: Fetcher;
}
