workers_dev = true
name = "based-chess-worker-nextjs"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets/" }

minify = true

# routes = [
#  { pattern = "bassedchess.xyz", custom_domain = true, zone_id="174377dee3e28c69ae81eb9f0d01fa66" }
# ]

[[durable_objects.bindings]]
name = "CHESS_GAME"
class_name = "ChessGame"
script_name = "chess-worker"

[[services]]
binding = "RPC_SERVICE"
service = "chess-worker"
entrypoint = "SessionsRPC"